application: huntsebirds
version: 1
runtime: python27
api_version: 1
threadsafe: no
default_expiration: "1d"

handlers:
- url: /(.*\.(gif|png|jpg|ico|js|css|swf|xml|json))
  static_files: \1
  upload: (.*\.(gif|png|jpg|ico|js|css|swf|xml|json))

- url: /(.*\.html)
  static_files: \1
  upload: (.*\.html)

- url: /.*
  script: main.app
